### ISSUE TITLE
Some weird Phenomenon happening with my relation when dealing with adding a page view

### ISSUE THREAD

**Issue by Teranode** [cyrildewit/laravel-page-view-counter#58] opened 2018-04-13 04:49 UTC
- Laravel Page View Counter Version: 2.0.0
- Laravel Version: 5.5.x-dev
- PHP Version: 7.2
- Database Driver & Version:

### Description:
I have no idea why this is happening, but I'm currently using OctoberCMS it has a relation called "attachOne" where it allows me to attach an image to the model via a relation (its basically a morph). What happens is that if it has no background and you visit the page the view will be counted twice. However if it does have a background, the view will be counted once. I'm not sure why this is happening.

**Comment by Teranode** [comment] 2018-04-13 09:02
The code is like this (the functions run on an execution based priority 
```
  public function onRun()
  {
      $this->comic = $this->page['comic'] = $this->loadComic();
      $this->comic->addView();

      $this->page->title = $this->comic->title;
  }

  protected function loadComic()
  {
      $id = $this->property('comic_id');

      $comic = ComicModel::with('genres')->whereId($id)->first();

      return $comic;
  }
```

yea the only wait to prevent it from running twice is to pass in if statement on the attachmany relation to verify if the background is there or not.

**Comment by cyrildewit** [comment] 2018-04-13 09:05
Is it possible that OctoberCMS runs this method multiple times?

**Comment by Teranode** [comment] 2018-04-13 09:16
I would have assumed the same thing, however iv'e tested it in other areas and it doesnt give me that kind of issue, but only when im using the background attachment

**Comment by cyrildewit** [comment] 2018-04-13 15:19
Add `\Log::debug("EL2_DEBUG | Added a new view for comic with id: {$comic->id}");` to the `onRun` method and reload that page one time. Take a look at the log file and check if it's being called multiple times. I'm pretty sure that this the problem is, but I want to verify it first before continuing.

**Comment by cyrildewit** [comment] 2018-04-17 06:59
Do you still encounter this issue? I actually think that this issue is not relevant to this package, so I am going to close it. You can still post questions and answers here.

Thanks!

**Closed by cyrildewit** 2018-04-17 06:59 UTC
